In [2]:
import numpy as np
import time

In [22]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

# Numpy

In [3]:
size = 1_000_000
# python lists
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print("python list time", end-start)
# numpy arrays
np_arr = np.array(py_list)
start = time.time()
# vectorization
sq_array =  np_arr **2
end = time.time()
print("numpy array time", end-start)

python list time 0.07728075981140137
numpy array time 0.002112150192260742


In [5]:
import sys
print(f"python list size= {sys.getsizeof(py_list)*len(py_list)} bytes")

python list size= 8000056000000 bytes


# Creating Arrays from lists

In [8]:
# create - from lists
arr = np.array([1,2,3,4,5])
print(arr, type(arr),arr.dtype,arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [11]:
# 2D array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape,arr2D.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int64


In [31]:
# create -Numpy arrays(using built in function)
arr1 = np.zeros((2,3),dtype="int64") # prefill with 0
print(arr1,arr1.shape,"\n")
# array filled with 1
arr2 = np.ones((2,3)) # prefill with 1
print(arr2,arr2.shape,"\n")

# prefill with choose no
arr3 = np.full((3,4),100)
print(arr3,arr3.shape,"\n")

# prefill with identity matrix (diagonal values are only 1 and other values are 0)
arr4 = np.eye(3)
print(arr4,arr4.shape,"\n")

# range elements
# range(start, end, step) (last step is excluded)
arr5 = np.arange(1,10,1)
print(arr5,arr5.shape)

# Evenly spaced arrays
arr6 = np.linspace(0,100,3)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3) 

[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) 

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3) 

[1 2 3 4 5 6 7 8 9] (9,)
[  0.  50. 100.] (3,)


In [41]:
# properties 
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim) # no of dimensions

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(2, 3)
6
int64
2
[[1. 2. 3.]
 [4. 5. 6.]] float64


# operations on Numpy Array

In [40]:
# Array Reshaping

In [48]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape,"\n")

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape,"\n")

#converts array in to 1D
flattened = arr.flatten() # 2D => 1D
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3) 

[[1 2]
 [3 4]
 [5 6]] (3, 2) 

[1 2 3 4 5 6] (6,)


In [49]:
# Indexing

In [55]:
arr = np.array([1,2,3,4,5,6])
print("Acces 1D array Element",arr[0],"\n")

# Indexing of 2D array
arr2D = np.array([[1,2,3],[4,5,6]])
print("Access 2D array Element",arr2D[0][1])

Acces 1D array Element 1 

Access 2D array Element 2


In [56]:
# Fancy Indexing
arr = np.array([1,2,3,4,5,6])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [57]:
# boolean indexing
arr = np.array([1,2,3,4,5,6])
print(arr[arr > 3])

[4 5 6]


In [62]:
# Slicing
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[::2]) # it is gives alternative elements
print(arr[::-1]) # lists in reverse order

[2 3 4]
[1 3 5]
[6 5 4 3 2 1]


In [66]:
arr = np.array([1,2,3,4,5,6])
print(arr, arr.dtype)

[1 2 3 4 5 6] int64


# Axes in Multi-Dimensional Arrays

In [11]:
# MultiDimensional Array
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))  # Total of all elements in the matrix

# Sum of colums
sum_of_columns = np.sum(arr2D,axis = 0)
print(sum_of_columns)

# Sum of Rows
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_colums)

# acess choose no from matrix
print("\n",arr2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[12 15 18]

 [[2]
 [5]]


In [13]:
array_3d = np.arange([[[],[]]])
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [20]:
arr_3d = np.array([
    [[1, 2],
     [3, 4],
     [5, 6]],

    [[7, 8],
     [9, 10],
     [11, 12]]
])
print(arr_3d,arr_3d.shape)

#indexing
print(arr_3d[1,1,0])

#slicing
print("\n slicing",arr_3d[:, 0, :])# first row from both layers

print("\n",arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9

 slicing [[1 2]
 [7 8]]

 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
# Braodcasting
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr.shape)
print(arr2.shape)

print(arr + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [30]:
# normalize
arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [34]:
arr = np.array([1,2,3,4,5])

print(np.argmax(arr))   # largest element index
print(np.argmin(arr))   # Smallest element index

4
0


In [37]:
# log
arr = np.array([1,2,3,4,5])
print(np.log(arr))  # natural log
print(np.log10(arr))  # log base 10
print(np.log2(arr))    #log base 2


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]


In [42]:
# Rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))   # points value will be removed

3.0
4.0
3.0
3.0


In [43]:
# Extras
arr = np.array([1,2,3,4,5])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
